name: tickteting_tool
description: "Tickteting_tool"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  intl:
  http:
  flutter_secure_storage:
  provider:
  url_launcher:
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img_1.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/img_1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
